### PR TITLE
Add version labels to all built images in image-autotag

### PR DESCRIPTION
**Pull request by tomjw64**
So... unfortunately this doesn't actually work even though it should and does not error... I'll just push this branch anyways because it's progress towards labeling and doesn't sacrifice any prior debug messages.

### CODE REVIEW

**Comment by rnathuji** [comment]
@tomjw64 - What was the issue you were seeing? I tried running this pipeline against a local registry, and when I do `docker inspect` on one of images I see:

```
"Labels": {
    "version_cops": "a4f2539",
    "version_cops_resource": "73c4635",
    "version_easybake": "bd47c6b",
    "version_mathify": "2ad5d21",
    "version_neb": "ca6651c",
    "version_princexml": "6bd2123",
    "version_recipes": "v1.51.0"
}
```

**Comment by tomjw64** [comment]
Oh! I was trying to pull from docker hub and checking the labels in the same way. Maybe I checked the wrong one!

**Comment by rnathuji** [comment]
Ah, I didn't realize the pipeline was already setup. Perhaps it is a concourse version issue? I looked at `openstax/output-producer-frontend:20200521.144952` and I don't see the labels on that. The one I built locally using the pipeline does.

**Comment by tomjw64** [comment]
Hmmmmm this might be something worth reporting if it is...

**Comment by rnathuji** [comment]
Just FYI @tomjw64 - I ran a quick test of v4.2.2 of Concourse locally, and no labels seemed to show up. I looked briefly at the [resource code](https://github.com/concourse/docker-image-resource/blob/master/assets/out) where the labels support came in [here](https://github.com/concourse/docker-image-resource/commit/fb7c6ed34580679528d06c1d1ecc7b8506e1d352). I'm wondering if this has something to do with the versions of things packaged inside of Concourse docker image? (e.g. is the version of the built-in `docker-image` the underlying issue?)

**Comment by tomjw64** [comment]
The thought occurred to me as well that the `docker-image` resource might be special and pinned with respect to each concourse version. An upgrade to 6.x might magically make this work.

**Comment by rnathuji** [comment]
Yes, I agree. I'm approving this since it works, we just won't get the goodness in production until we upgrade our Concourse version.

**Pull request merged**
